#!/usr/bin/env node
/**
 * Sync note folders from /notes into the VitePress site.
 * Registry: docs/hello-agent/index.md frontmatter `tutorials` array.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "yaml";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const notesDir = path.join(root, "notes");
const helloAgentDocs = path.join(root, "docs/hello-agent");
const publicHelloAgent = path.join(root, "docs/public/hello-agent");
const indexPath = path.join(helloAgentDocs, "index.md");
const sidebarPath = path.join(root, "docs/.vitepress/hello-agent-sidebar.json");

function readRegistry() {
  const raw = fs.readFileSync(indexPath, "utf8");
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) {
    throw new Error(`Missing frontmatter in ${indexPath}`);
  }
  const fm = yaml.parse(match[1]);
  const tutorials = fm.tutorials;
  if (!Array.isArray(tutorials) || tutorials.length === 0) {
    throw new Error("`tutorials` must be a non-empty array in hello-agent/index.md frontmatter");
  }
  for (const t of tutorials) {
    for (const key of ["slug", "folder", "html", "title", "description"]) {
      if (!t[key]) {
        throw new Error(`Tutorial entry missing "${key}": ${JSON.stringify(t)}`);
      }
    }
  }
  return { fm, tutorials, raw };
}

function syncPublicAssets(tutorials) {
  fs.rmSync(publicHelloAgent, { recursive: true, force: true });
  fs.mkdirSync(publicHelloAgent, { recursive: true });

  for (const t of tutorials) {
    const srcDir = path.join(notesDir, t.folder);
    if (!fs.existsSync(srcDir)) {
      throw new Error(`Notes folder not found: notes/${t.folder}`);
    }

    const destDir = path.join(publicHelloAgent, t.slug);
    fs.mkdirSync(destDir, { recursive: true });

    for (const entry of fs.readdirSync(srcDir)) {
      if (entry.endsWith(".pdf")) continue;
      const from = path.join(srcDir, entry);
      const to = path.join(destDir, entry);
      fs.cpSync(from, to, { recursive: true });
    }

    const srcHtml = path.join(destDir, t.html);
    const destHtml = path.join(destDir, `${t.slug}-document.html`);
    if (!fs.existsSync(srcHtml)) {
      throw new Error(`HTML not found: notes/${t.folder}/${t.html}`);
    }
    fs.renameSync(srcHtml, destHtml);
  }
}

function syncMarkdownPages(tutorials) {
  const generated = new Set(tutorials.map((t) => `${t.slug}.md`));

  for (const t of tutorials) {
    const mdPath = path.join(helloAgentDocs, `${t.slug}.md`);
    const titleYaml = yaml.stringify(t.title).trim();
    const titleAttr = t.title.replace(/"/g, "&quot;");
    const body = `---
layout: page
title: false
pageClass: hello-agent-tutorial
---

<!-- Auto-generated by scripts/sync-notes.mjs — do not edit -->
<HelloAgentEmbed slug="${t.slug}" title="${titleAttr}" />
`;
    fs.writeFileSync(mdPath, body, "utf8");
  }

  for (const entry of fs.readdirSync(helloAgentDocs)) {
    if (!entry.endsWith(".md") || entry === "index.md") continue;
    if (!generated.has(entry)) {
      fs.rmSync(path.join(helloAgentDocs, entry));
      console.log(`removed stale page: hello-agent/${entry}`);
    }
  }
}

function syncSidebar(tutorials) {
  const sidebar = [
    {
      text: "Hello Agent",
      link: "/hello-agent/",
      items: [
        { text: "Overview", link: "/hello-agent/" },
        ...tutorials.map((t) => ({
          text: t.sidebarTitle ?? t.title,
          link: `/hello-agent/${t.slug}`
        }))
      ]
    }
  ];
  fs.writeFileSync(sidebarPath, `${JSON.stringify(sidebar, null, 2)}\n`, "utf8");
}

function syncIndexTable(tutorials, raw) {
  const rows = tutorials
    .map((t) => `| [${t.title}](./${t.slug}) | ${t.description} |`)
    .join("\n");
  const block = `| Tutorial | Description |\n| --- | --- |\n${rows}`;

  const start = "<!-- tutorials-table:begin -->";
  const end = "<!-- tutorials-table:end -->";
  if (!raw.includes(start) || !raw.includes(end)) {
    throw new Error(`Missing ${start} / ${end} markers in hello-agent/index.md`);
  }

  const updated = raw.replace(
    new RegExp(`${start}[\\s\\S]*?${end}`),
    `${start}\n${block}\n${end}`
  );
  fs.writeFileSync(indexPath, updated, "utf8");
}

function main() {
  const { tutorials, raw } = readRegistry();
  syncPublicAssets(tutorials);
  syncMarkdownPages(tutorials);
  syncSidebar(tutorials);
  syncIndexTable(tutorials, raw);
  console.log(`synced ${tutorials.length} tutorial(s) from notes/`);
}

main();
